### ISSUE TITLE
[BUG] can not use DFR or DFR_LOCAL on functions with multiple protoype definitions

### ISSUE THREAD

**Issue by 0xShkk** [Cobalt-Strike/bof-vs#2]
Thank you for providing this new approach for BOF development. It really eases the dev speed and debugging capabilities.

Recently, I wanted to use `getaddrinfo`, described [here](https://learn.microsoft.com/de-de/windows/win32/api/ws2tcpip/nf-ws2tcpip-getaddrinfo). However, it is not possible to resolve the function address dynamically for this function.

Tried like  
```
    DFR(WS2_32, getaddrinfo);
    #define getaddrinfo WS2_32$getaddrinfo
```
and

```
DFR_LOCAL(WS2_32, getaddrinfo);
```

both fails with an error, that VS does not find the function definition.

It is also the case for `freeaddrinfo`.

How could such functions be resolved with the new `DFR` macros. This should be the case for all functions inheriting multiple prototype definitions?

**Comment by Henkru** [comment]
Hi,

Thanks for the feedback. Did you include the `ws2tcpip.h` header which declares the `getaddrinfo` function? The DFR macros uses the [decltype](https://en.cppreference.com/w/cpp/language/decltype) specifier to extract the function type, and therefore the function must be declared at the time when the DFR macro is used.

I wasn't able to reproduce the issue, and I crafted the following example, which uses the `getaddrinfo`  (defined by the `DFR_LOCAL` macro) to lookup `google.com`. I'll close this, but let me know if the solution below does not fix your issue.

```c++
#include <ws2tcpip.h>
#include <winsock.h>
#include <Windows.h>

#include "base\helpers.h"

#ifdef _DEBUG
// The debug build requires the lib be linked
#pragma comment (lib, "Ws2_32.lib")

#undef DECLSPEC_IMPORT
#define DECLSPEC_IMPORT
#include "base\mock.h"
#endif // _DEBUG

extern "C" {
#include "beacon.h"
#include "sleepmask.h"

void go(char* args, int len) {
    DFR_LOCAL(Ws2_32, WSAStartup);
    DFR_LOCAL(Ws2_32, getaddrinfo);
    DFR_LOCAL(Ws2_32, ntohs);
    DFR_LOCAL(Ws2_32, inet_ntop);

    WSADATA wsaData = { 0 };
    int wsInitRes = WSAStartup(MAKEWORD(2, 2), &wsaData);
    if (wsInitRes != 0) {
        BeaconPrintf(CALLBACK_ERROR, "WSAStartup failed: %d\n", wsInitRes);
        return;
    }

    struct addrinfo* res = NULL;
    DWORD result = getaddrinfo("google.com", "https", NULL, &res);
    if (result != 0) {
        BeaconPrintf(CALLBACK_ERROR, "getaddrinfo failed: %d\n", result);
        return;
    }

    for (struct addrinfo* i = res; i != NULL; i = i->ai_next) {
        char str[INET6_ADDRSTRLEN];
        if (i->ai_addr->sa_family == AF_INET) {
            struct sockaddr_in* p = (struct sockaddr_in*)i->ai_addr;
            int port = ntohs(p->sin_port);
            BeaconPrintf(CALLBACK_OUTPUT, "%s: %i\n", inet_ntop(AF_INET, &p->sin_addr, str, sizeof(str)), port);
        }
        else if (i->ai_addr->sa_family == AF_INET6) {
            struct sockaddr_in6* p = (struct sockaddr_in6*)i->ai_addr;
            int port = ntohs(p->sin6_port);
            BeaconPrintf(CALLBACK_OUTPUT, "%s: %i\n", inet_ntop(AF_INET6, &p->sin6_addr, str, sizeof(str)), port);
        }
    }
}

}

#if defined(_DEBUG)
int main(int argc, char* argv[]) {
    bof::runMocked<>(go);
    return 0;
}
#endif // _DEBUG
```
```
[10/23 05:23:04] beacon> inline-execute bof.x64.o
[10/23 05:23:04] [*] Tasked beacon to inline-execute bof.x64.o
[10/23 05:23:07] [+] host called home, sent: 1125 bytes
[10/23 05:23:07] [+] received output:
216.58.209.206: 443
```

**Comment by 0xShkk** [comment]
Sorry for the late heads-up but I have found out why it did not work for me on the first try.  

Your code snippet made me analyse my code and look for differences. Thank you for that, much appreciated.  

So to reproduce my initial import error in VS, simply include your headers on top in this order:

```
#include <windows.h>
#include <winsock.h>
#include <ws2tcpip.h>
```

Adding the `windows.h` header last, fixes all errors.
```
#include <winsock.h>
#include <ws2tcpip.h>
#include <windows.h>
```
